// ──────────────────────────────────────────────────────────
// LOKSHIFT CORE TYPES
// ──────────────────────────────────────────────────────────

import { 
  LeadRow, 
  TechnicianRow, 
  JobRow, 
  MatchResult as MatchResultDB, 
  QualificationResult as QualificationResultDB 
} from './types/database.types'

export type UserRole = 'admin' | 'dispatcher' | 'employee'
export type Lead = LeadRow
export type Technician = TechnicianRow
export type Job = JobRow
export type MatchResult = MatchResultDB
export type QualificationResult = QualificationResultDB

export const EVENT_COLORS = {
  birthday:   '#A78BFA',  // purple
  meeting:    '#60A5FA',  // blue
  shift:      '#F472B6',  // pink
  sick_leave: '#10B981',  // green (emerald-500)
  event:      '#0064E0',  // default blue
  holiday:    '#F59E0B',  // yellow (amber-500)
  other:      '#94A3B8',  // gray
} as const

export interface Profile {
  id: string
  organization_id: string | null
  full_name: string | null
  email: string | null
  role: UserRole
  avatar_url: string | null
  is_active: boolean
  onboarding_completed: boolean
  target_hours: number
  working_time_model_id?: string | null
  last_lat: number | null
  last_lng: number | null
  last_location_update: string | null
  created_at: string
  updated_at: string
}

export interface WorkingTimeModel {
  id: string
  organization_id: string
  name: string
  description: string | null
  target_hours_per_week: number
  is_active: boolean
  created_at: string
  updated_at: string
}

export interface Organization {
  id: string
  name: string
  slug: string
  logo_url: string | null
  settings: Record<string, any>
  created_at: string
  updated_at: string
}

export interface Customer {
  id: string
  organization_id: string
  name: string
  address: string | null
  contact_person: string | null
  contact_info: string | null // Legacy field
  email: string | null
  phone: string | null
  notes: string | null
  latitude: number | null
  longitude: number | null
  is_active: boolean
  created_at: string
  updated_at: string
}

export interface Plan {
  id: string
  organization_id: string
  employee_id: string
  creator_id: string
  customer_id: string | null
  start_time: string
  end_time: string
  route: string | null
  location: string | null
  notes: string | null
  status: 'draft' | 'assigned' | 'confirmed' | 'rejected' | 'cancelled'
  rejection_reason: string | null
  created_at: string
  updated_at: string
  // Joined fields
  employee?: Profile
  customer?: Customer
}

export interface TimeEntry {
  id: string
  organization_id: string
  employee_id: string
  plan_id?: string
  customer_id?: string
  date: string                    // 'YYYY-MM-DD'
  start_time: string              // ISO timestamp
  end_time: string                // ISO timestamp
  break_minutes: number
  net_hours: number               // READ ONLY — GENERATED by Postgres
  notes?: string
  location?: string
  latitude?: number | null
  longitude?: number | null
  is_verified: boolean
  verified_by?: string
  is_on_break?: boolean             // Real-time status
  current_break_start?: string     // ISO timestamp
  total_break_seconds?: number     // Accumulated
  created_at: string
  updated_at: string
  // Joined
  employee?: Profile
  customer?: { id: string; name: string }
  verifier?: { id: string; full_name: string }
  plan?: { location?: string; customer?: { id: string; name: string } }
}

export interface MonthlyTimeData {
  key: string                     // 'YYYY-MM'
  year: number
  month: number
  workingDays: number
  scheduledHours: number
  actualHours: number
  difference: number              // positive = overtime, negative = deficit
  entries: TimeEntry[]
}

export interface TimeEntryFormData {
  date: string
  startTime: string              // 'HH:MM'
  endTime: string                // 'HH:MM'
  breakMinutes: number
  customerId?: string
  location?: string
  notes?: string
}

export interface TimeAccount {
  employee_id: string
  full_name: string
  target_hours: number
  actual_hours: number
  balance: number
}

export interface PerDiem {
  id: string
  organization_id: string
  employee_id: string
  plan_id?: string | null          // Linked mission plan
  date: string
  task: string | null
  start_date: string | null
  end_date: string | null
  num_days: number
  rate: number
  hourly_rate?: number             // New: hourly charge rate
  working_hours?: number           // New: hours worked
  departure_time: string | null
  return_time: string | null
  country: string
  amount: number
  status: 'submitted' | 'approved' | 'rejected'
  notes: string | null
  created_at: string
  updated_at: string
  // Joined fields
  plan?: Plan
}

export interface HolidayBonus {
  id: string
  organization_id: string
  employee_id: string
  amount: number
  period_start: string | null
  period_end: string | null
  notes: string | null
  created_at: string
}

export interface ChatConversation {
  id: string
  organization_id: string
  name: string | null
  is_group: boolean
  created_by: string
  created_at: string
  updated_at: string
  // Joined fields
  members?: ChatMember[]
  last_message?: ChatMessage
  messages?: ChatMessage[]
  unread_count?: number
}

export interface ChatMember {
  conversation_id: string
  user_id: string
  role: 'admin' | 'member'
  joined_at: string
  last_read_at: string
  profile?: Profile
}

export interface ChatMessage {
  id: string
  conversation_id: string
  sender_id: string
  content: string | null
  attachment_url: string | null
  created_at: string
  // Joined fields
  sender?: Profile
}

export interface UserWithProfile {
  id: string
  email: string
  profile: Profile | null
}

export interface Notification {
  id: string
  user_id: string
  title: string
  message: string
  module_type: string
  module_id?: string
  is_read: boolean
  created_at: string
}

export type CalendarEventType = 'event' | 'shift' | 'birthday' | 'meeting' | 'sick_leave' | 'holiday' | 'other'

export interface CalendarEvent {
  id: string
  organization_id: string
  creator_id: string
  title: string
  description: string | null
  event_type: CalendarEventType
  start_time: string        // ISO timestamp
  end_time: string          // ISO timestamp
  is_all_day: boolean
  color: string
  location: string | null
  created_at: string
  updated_at: string
  // Optional joined fields
  creator?: Profile
  members?: { user: Profile }[]
}

export interface CalendarEventMember {
  event_id: string
  user_id: string
  profile?: Profile
}

export interface CalendarEventFormData {
  title: string
  description?: string
  event_type: CalendarEventType
  start_time: string
  end_time: string
  is_all_day: boolean
  color: string
  location?: string
  member_ids: string[]
}
